apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingressWithCicd
spec:
  replicas: 2
  selector:
    matchLabels:
      app1: web1
  template: 
   metadata:
     labels:
       app1: web1
   spec:
     containers:
       - name: con1
         image: img
         imagePullPolicy: Always
         ports:
           - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: web
    name: first
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  type: LoadBalancer
  selector:
    app1: web1
